title: Dr Jakub Krukar
logo: "/images/1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral Researcher/Lecturer
  Institute for Geoinformatics, University of Muenster, Germany
   <br><br>
  I am a researcher and lecturer in spatial cognition - a branch of cognitive science studying how people think about, think in, and think with space.

  I am a psychologist by training and I apply psychological methods in the fields of geoinformatics, architecture, and human-computer interaction.
  <br><br>

  <a href="/pdfs/cv.pdf">--- my CV</a>

  <a href="https://scholar.google.de/citations?user=-c7yB1IAAAAJ&hl=en&oi=ao">--- my Google Scholar</a>

  <a href="https://orcid.org/0000-0003-2615-8757">--- my ORCID</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-104760669-1 # your Google Analytics tracking ID here
