title: Dr Jakub Krukar
logo: "/images/1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral Researcher/Lecturer
  <a href="https://ifgi.uni-muenster.de">Institute for Geoinformatics, 
  
  University of Muenster, Germany</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-104760669-1 # your Google Analytics tracking ID here
